"use client";

import { useEffect, useMemo, useState, useTransition } from "react";
import { AlertTriangle, CheckCircle2, ClipboardCheck, Lock, Plus, RotateCcw } from "lucide-react";
import { useAuth } from "@/lib/auth";
import {
  AccountingAccountRow,
  AccountingPeriodRow,
  createJournalEntry,
  isMissingTaxSchema,
  loadAccountingPeriod,
  loadAccountingWorkspace,
  saveAccountingPeriod,
} from "@/lib/pajak/store";
import { monthEndDate } from "@/lib/pajak/reconciliation";

type Template = "accrual" | "depreciation" | "prepaid" | "inventory_down" | "inventory_up" | "income_tax";
const colors={ink:"#3C2F2F",med:"#7C685B",line:"#E6D5BE",soft:"#F6EEE6",accent:"#A67B5B",green:"#15803D",amber:"#9A6700",red:"#B91C1C"};
const field:React.CSSProperties={width:"100%",border:`1px solid ${colors.line}`,borderRadius:7,padding:"8px 9px",fontSize:10,color:colors.ink,background:"white",outline:"none"};
const labels:Record<Template,string>={accrual:"Beban masih harus dibayar",depreciation:"Penyusutan aset",prepaid:"Biaya dibayar di muka",inventory_down:"Koreksi persediaan berkurang",inventory_up:"Koreksi persediaan bertambah",income_tax:"Beban pajak penghasilan"};
const rp=(value:number)=>`Rp ${Math.round(value).toLocaleString("id-ID")}`;

export default function AccountingPeriodClose({year,month}:{year:number;month:number}){
 const{user}=useAuth();const period=`${year}-${String(month).padStart(2,"0")}`,start=`${period}-01`,end=monthEndDate(year,month);
 const[accounts,setAccounts]=useState<AccountingAccountRow[]>([]),[journals,setJournals]=useState<Awaited<ReturnType<typeof loadAccountingWorkspace>>["journals"]>([]),[periodRow,setPeriodRow]=useState<AccountingPeriodRow|null>(null);
 const[template,setTemplate]=useState<Template>("accrual"),[expenseCode,setExpenseCode]=useState("6102"),[date,setDate]=useState(end),[description,setDescription]=useState(""),[amount,setAmount]=useState(0),[notes,setNotes]=useState(""),[message,setMessage]=useState(""),[pending,startTransition]=useTransition();
 const optionalPeriod=()=>loadAccountingPeriod(period).catch(error=>{if(isMissingTaxSchema(error)){setMessage("Jalankan migration laporan akuntansi agar periode dapat dikunci.");return null}throw error});
 const reload=()=>Promise.all([loadAccountingWorkspace(start,end),optionalPeriod()]).then(([workspace,current])=>{setAccounts(workspace.accounts);setJournals(workspace.journals);setPeriodRow(current);}).catch(error=>setMessage(`Gagal memuat tutup buku: ${(error as{message?:string}).message??"kesalahan database"}`));
 useEffect(()=>{let active=true;Promise.all([loadAccountingWorkspace(start,end),loadAccountingPeriod(period).catch(error=>{if(isMissingTaxSchema(error))return null;throw error})]).then(([workspace,current])=>{if(active){setAccounts(workspace.accounts);setJournals(workspace.journals);setPeriodRow(current);if(!current)setMessage("Jalankan migration laporan akuntansi agar periode dapat dikunci.")}}).catch(()=>{if(active)setMessage("Gagal memuat data tutup buku.")});return()=>{active=false}},[period,start,end]);
 const accountByCode=useMemo(()=>new Map(accounts.map(account=>[account.code,account])),[accounts]);
 const expenseAccounts=accounts.filter(account=>account.account_type==="expense");
 const diagnostics=useMemo(()=>{let debit=0,credit=0;for(const journal of journals)for(const line of journal.journal_lines??[]){debit+=Number(line.debit||0);credit+=Number(line.credit||0)}return{drafts:journals.filter(j=>j.status==="draft").length,debit,credit,difference:debit-credit}},[journals]);
 const status=periodRow?.status??"open",closed=status==="closed";
 const adjustmentAccounts=()=>{let debitCode=expenseCode,creditCode="2103";if(template==="depreciation"){debitCode="6109";creditCode="1591"}if(template==="prepaid"){debitCode="1401";creditCode=expenseCode}if(template==="inventory_down"){debitCode="5101";creditCode="1301"}if(template==="inventory_up"){debitCode="1301";creditCode="5101"}if(template==="income_tax"){debitCode="8201";creditCode="2102"}return{debit:accountByCode.get(debitCode),credit:accountByCode.get(creditCode)}};
 const addAdjustment=()=>startTransition(async()=>{const pair=adjustmentAccounts();if(closed){setMessage("Periode sudah ditutup dan tidak dapat menerima jurnal baru.");return}if(!pair.debit||!pair.credit){setMessage("Akun penyesuaian belum tersedia. Jalankan migration laporan akuntansi.");return}if(amount<=0||!description.trim()){setMessage("Isi keterangan dan nominal penyesuaian.");return}try{await createJournalEntry({entry_date:date,reference:`ADJ-${period}-${Date.now().toString().slice(-6)}`,description:description.trim(),created_by:user?.username??"finance",source_type:"adjustment",source_id:`adjustment:${crypto.randomUUID()}`,lock:true,lines:[{account_id:pair.debit.id,description:labels[template],debit:amount,credit:0,line_no:1},{account_id:pair.credit.id,description:labels[template],debit:0,credit:amount,line_no:2}]});setDescription("");setAmount(0);setMessage("Jurnal penyesuaian berhasil dibukukan.");await reload()}catch(error){setMessage(`Penyesuaian gagal: ${(error as{message?:string}).message??"kesalahan database"}`)}});
 const changeStatus=(next:AccountingPeriodRow["status"])=>startTransition(async()=>{if(next==="closed"&&!window.confirm(`Tutup periode ${period}? Jurnal dan transaksi yang sudah dibukukan tidak dapat diubah.`))return;try{const now=new Date().toISOString();const saved=await saveAccountingPeriod({workspace:"toto",period,status:next,notes,reviewed_by:next!=="open"?user?.username??"":"",reviewed_at:next!=="open"?now:null,closed_by:next==="closed"?user?.username??"":"",closed_at:next==="closed"?now:null});setPeriodRow(saved);setMessage(next==="closed"?"Periode berhasil ditutup.":next==="review"?"Periode ditandai siap review.":"Periode dibuka kembali.")}catch(error){setMessage(`Status periode tidak berubah: ${(error as{message?:string}).message??"periksa transaksi dan HPP yang belum selesai"}`)}});
 return <div style={{display:"grid",gap:12}}>
  {message?<div role="status" style={{display:"flex",gap:7,padding:10,border:`1px solid ${colors.line}`,background:"white",borderRadius:8,fontSize:10,color:colors.med}}><AlertTriangle size={14}/><span style={{flex:1}}>{message}</span><button onClick={()=>setMessage("")} style={{border:0,background:"transparent",fontWeight:700,color:"inherit",cursor:"pointer"}}>Tutup</button></div>:null}
  <section style={{background:"white",border:`1px solid ${colors.line}`,borderRadius:10,padding:14}}><div style={{display:"flex",alignItems:"flex-start",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><div style={{display:"flex",alignItems:"center",gap:6,fontSize:12,fontWeight:800}}><ClipboardCheck size={17} color={colors.accent}/>Kontrol periode {period}</div><p style={{fontSize:10,color:colors.med,margin:"5px 0 0"}}>Tutup periode hanya berhasil jika transaksi Keuangan sudah masuk jurnal, tidak ada jurnal draft, dan HPP terkirim sudah selesai.</p></div><span style={{padding:"6px 9px",borderRadius:6,fontSize:10,fontWeight:800,background:closed?"#F0FBF3":status==="review"?"#FFF9E8":colors.soft,color:closed?colors.green:status==="review"?colors.amber:colors.med}}>{closed?"Periode ditutup":status==="review"?"Menunggu review":"Periode terbuka"}</span></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:8,marginTop:12}}>{[["Jurnal periode",journals.length],["Jurnal draft",diagnostics.drafts],["Total debit",rp(diagnostics.debit)],["Selisih debit-kredit",rp(diagnostics.difference)]].map(([label,value])=><div key={String(label)} style={{background:colors.soft,borderRadius:7,padding:9}}><div style={{fontSize:9,color:colors.med}}>{label}</div><b style={{fontSize:12,display:"block",marginTop:4,color:label==="Selisih debit-kredit"&&Number(diagnostics.difference)!==0?colors.red:colors.ink}}>{String(value)}</b></div>)}</div><label style={{display:"grid",gap:4,fontSize:9,fontWeight:700,color:colors.med,marginTop:10}}>Catatan review<textarea value={notes} onChange={event=>setNotes(event.target.value)} style={{...field,minHeight:58,resize:"vertical"}} placeholder="Selisih, koreksi, atau persetujuan konsultan"/></label><div style={{display:"flex",justifyContent:"flex-end",gap:7,marginTop:9,flexWrap:"wrap"}}>{status==="open"?<button disabled={pending} onClick={()=>changeStatus("review")} style={{border:`1px solid ${colors.line}`,background:"white",borderRadius:7,padding:"8px 10px",fontSize:10,fontWeight:800,cursor:"pointer"}}>Kirim untuk review</button>:null}{!closed?<button disabled={pending} onClick={()=>changeStatus("closed")} style={{border:0,background:colors.accent,color:"white",borderRadius:7,padding:"8px 10px",fontSize:10,fontWeight:800,display:"flex",gap:5,alignItems:"center",cursor:"pointer"}}><Lock size={12}/>Tutup periode</button>:user?.role==="owner"?<button disabled={pending} onClick={()=>changeStatus("open")} style={{border:`1px solid ${colors.line}`,background:"white",borderRadius:7,padding:"8px 10px",fontSize:10,fontWeight:800,display:"flex",gap:5,alignItems:"center",cursor:"pointer"}}><RotateCcw size={12}/>Buka kembali</button>:null}</div></section>
  <section style={{background:"white",border:`1px solid ${colors.line}`,borderRadius:10,overflow:"hidden",opacity:closed ? .65 : 1}}><div style={{padding:"12px 14px",borderBottom:`1px solid ${colors.line}`}}><h2 style={{fontSize:13,margin:0}}>Penyesuaian tutup buku</h2><p style={{fontSize:9,color:colors.med,margin:"4px 0 0"}}>Form terpandu untuk transaksi nonkas seperti akrual, penyusutan, dan koreksi persediaan.</p></div><div style={{padding:14,display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:9}}><label style={{fontSize:9,fontWeight:700,color:colors.med}}>Jenis penyesuaian<select disabled={closed} value={template} onChange={event=>setTemplate(event.target.value as Template)} style={{...field,marginTop:4}}>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>{template==="accrual"||template==="prepaid"?<label style={{fontSize:9,fontWeight:700,color:colors.med}}>Akun beban<select disabled={closed} value={expenseCode} onChange={event=>setExpenseCode(event.target.value)} style={{...field,marginTop:4}}>{expenseAccounts.map(account=><option key={account.id} value={account.code}>{account.code} · {account.name}</option>)}</select></label>:null}<label style={{fontSize:9,fontWeight:700,color:colors.med}}>Tanggal<input disabled={closed} type="date" min={start} max={end} value={date} onChange={event=>setDate(event.target.value)} style={{...field,marginTop:4}}/></label><label style={{fontSize:9,fontWeight:700,color:colors.med}}>Nominal<input disabled={closed} type="number" min="0" value={amount||""} onChange={event=>setAmount(Number(event.target.value))} style={{...field,marginTop:4,textAlign:"right"}} placeholder="0"/></label><label style={{fontSize:9,fontWeight:700,color:colors.med,gridColumn:"1 / -1"}}>Keterangan<input disabled={closed} value={description} onChange={event=>setDescription(event.target.value)} style={{...field,marginTop:4}} placeholder="Contoh: penyusutan mesin produksi September"/></label><div style={{gridColumn:"1 / -1",display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",flexWrap:"wrap"}}><span style={{fontSize:9,color:colors.med}}>{(()=>{const pair=adjustmentAccounts();return pair.debit&&pair.credit?`Debit ${pair.debit.code} ${pair.debit.name} · Kredit ${pair.credit.code} ${pair.credit.name}`:"Akun belum tersedia"})()}</span><button disabled={pending||closed} onClick={addAdjustment} style={{border:0,background:closed?"#C9B8AA":colors.accent,color:"white",borderRadius:7,padding:"8px 10px",fontSize:10,fontWeight:800,display:"flex",gap:5,alignItems:"center",cursor:closed?"not-allowed":"pointer"}}><Plus size={12}/>Bukukan penyesuaian</button></div></div></section>
  {closed?<div style={{display:"flex",alignItems:"center",gap:7,padding:10,border:"1px solid #BBE2C5",background:"#F0FBF3",borderRadius:8,color:colors.green,fontSize:10}}><CheckCircle2 size={15}/>Periode telah dikunci. Laporan periode ini menjadi arsip pembukuan.</div>:null}
 </div>
}
