"use client";
import { useEffect,useMemo,useState,useTransition } from "react";
import { AlertTriangle,CheckCircle2,ChevronDown,Link2,RefreshCw } from "lucide-react";
import { useAuth } from "@/lib/auth";
import { useStore } from "@/lib/store";
import { AccountingAccountRow,AccountingMappingRow,createJournalEntry,isMissingTaxSchema,JournalEntryRow,loadAccountingWorkspace } from "@/lib/pajak/store";
import { monthEndDate } from "@/lib/pajak/reconciliation";

type Props={year:number;month:number};
const med="#7C685B",line="#E6D5BE",soft="#F6EEE6",accent="#A67B5B";
const rp=(v:number)=>`Rp ${Math.round(v).toLocaleString("id-ID")}`;

export default function AccountingJournal({year,month}:Props){
 const {user}=useAuth(),{cashFlow,loading:cashLoading}=useStore();
 const [accounts,setAccounts]=useState<AccountingAccountRow[]>([]),[mappings,setMappings]=useState<AccountingMappingRow[]>([]),[journals,setJournals]=useState<JournalEntryRow[]>([]);
 const [message,setMessage]=useState(""),[schemaReady,setSchemaReady]=useState(true),[expandedId,setExpandedId]=useState<string|null>(null),[isPending,startTransition]=useTransition();
 const start=`${year}-${String(month).padStart(2,"0")}-01`,end=monthEndDate(year,month);
 const applyData=(d:Awaited<ReturnType<typeof loadAccountingWorkspace>>)=>{setAccounts(d.accounts);setJournals(d.journals);setMappings(d.mappings);setSchemaReady(true)};
 const reload=()=>loadAccountingWorkspace(start,end).then(applyData).catch(e=>{setSchemaReady(false);setMessage(isMissingTaxSchema(e)?"Jalankan migrasi akuntansi dan integrasi Keuangan terlebih dahulu.":"Gagal memuat data jurnal.")});
 useEffect(()=>{let cancelled=false;loadAccountingWorkspace(start,end).then(d=>{if(!cancelled)applyData(d)}).catch(e=>{if(!cancelled){setSchemaReady(false);setMessage(isMissingTaxSchema(e)?"Jalankan migrasi akuntansi dan integrasi Keuangan terlebih dahulu.":"Gagal memuat data jurnal.")}});return()=>{cancelled=true}},[start,end]);
 const financeJournals=useMemo(()=>journals.filter(j=>j.source_type==="cash_flow"),[journals]);
 const totals=useMemo(()=>financeJournals.map(j=>({...j,total:(j.journal_lines??[]).reduce((s,l)=>s+Number(l.debit||0),0)})),[financeJournals]);
 const posted=useMemo(()=>new Set(journals.filter(j=>j.source_type==="cash_flow"&&j.source_id).map(j=>j.source_id!)),[journals]);
 const preview=useMemo(()=>cashFlow.filter(c=>!c.isTest&&!c.isAdjustment&&!c.transferGroup&&c.date>=start&&c.date<=end&&!posted.has(c.id)).map(cf=>{const target=mappings.find(m=>m.flow_type===cf.type&&m.source_category===cf.category),cashAccount=accounts.find(a=>a.code===(/cash|kas/i.test(cf.bankAccount)?"1101":"1102"));return{cf,target,cashAccount,ready:!!target&&!!cashAccount}}),[cashFlow,start,end,posted,mappings,accounts]);
 const ready=preview.filter(x=>x.ready),unmapped=preview.filter(x=>!x.ready);
 const sync=()=>startTransition(async()=>{if(!schemaReady){setMessage("Integrasi database Akuntansi belum siap.");return}if(!ready.length){setMessage("Tidak ada transaksi Keuangan yang siap disinkronkan.");return}if(!window.confirm(`Buat dan kunci ${ready.length} jurnal dari menu Keuangan?`))return;let success=0;for(const{cf,target,cashAccount}of ready){if(!target||!cashAccount)continue;const debit=cf.type==="income"?cashAccount.id:target.account_id,credit=cf.type==="income"?target.account_id:cashAccount.id;try{await createJournalEntry({entry_date:cf.date,reference:`KEU-${cf.id.slice(0,8)}`,description:cf.description||cf.category,created_by:user?.username??"",source_type:"cash_flow",source_id:cf.id,lock:true,lines:[{account_id:debit,description:cf.category,debit:cf.amount,credit:0,line_no:1},{account_id:credit,description:cf.category,debit:0,credit:cf.amount,line_no:2}]});success++}catch(e){if((e as{code?:string}).code!=="23505"){setMessage(`Sinkronisasi berhenti setelah ${success} jurnal: ${(e as{message?:string}).message??"kesalahan database"}`);await reload();return}}}setMessage(`${success} transaksi Keuangan berhasil dibukukan tanpa input ulang.`);await reload()});
 return <div style={{display:"grid",gap:12}}>
  <section style={{background:"white",border:`1px solid ${line}`,borderRadius:10,padding:12,display:"flex",alignItems:"center",gap:12,flexWrap:"wrap"}}><div style={{width:34,height:34,borderRadius:8,background:soft,color:accent,display:"flex",alignItems:"center",justifyContent:"center"}}><Link2 size={17}/></div><div><b style={{fontSize:12}}>Transaksi dari Keuangan</b><div style={{fontSize:10,color:med,marginTop:2}}>{cashLoading?"Memuat transaksi...":`${ready.length} belum masuk jurnal · ${posted.size} sudah masuk`}</div></div><button disabled={isPending||cashLoading||!ready.length} onClick={sync} style={{marginLeft:"auto",border:0,background:ready.length?accent:"#C9B8AA",color:"white",borderRadius:7,padding:"8px 11px",fontSize:11,fontWeight:700,cursor:ready.length?"pointer":"not-allowed",display:"flex",alignItems:"center",gap:5}}><RefreshCw size={13}/>{isPending?"Memproses...":"Sinkronkan"}</button>{unmapped.length?<div style={{width:"100%",fontSize:10,color:"#875F13",background:"#FFF9E8",padding:"7px 9px",borderRadius:6}}>{unmapped.length} transaksi ditahan karena kategori belum dikenali: {[...new Set(unmapped.map(x=>x.cf.category))].join(", ")}.</div>:null}</section>
  {message?<div role="status" style={{display:"flex",gap:7,padding:9,border:"1px solid #F3D08B",background:"#FFF9E8",borderRadius:7,fontSize:10,color:"#875F13"}}><AlertTriangle size={14}/>{message}</div>:null}
  <section style={{background:"white",border:`1px solid ${line}`,borderRadius:10,overflow:"hidden"}}><div style={{padding:"12px 14px",borderBottom:`1px solid ${line}`,display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><h2 style={{fontSize:14,margin:0}}>Jurnal</h2><p style={{fontSize:10,color:med,margin:"3px 0 0"}}>{start} sampai {end}</p></div><span style={{fontSize:11,fontWeight:700,color:med}}>{financeJournals.length} transaksi</span></div><div style={{maxHeight:650,overflow:"auto"}}>{!totals.length?<div style={{padding:24,textAlign:"center",fontSize:11,color:med}}>Belum ada jurnal. Klik Sinkronkan.</div>:totals.map(j=>{const open=expandedId===j.id;return <div key={j.id} style={{borderBottom:`1px solid ${soft}`}}><button type="button" aria-expanded={open} onClick={()=>setExpandedId(open?null:j.id)} style={{width:"100%",padding:"11px 13px",border:0,background:open?"#FFFBF7":"white",display:"flex",alignItems:"center",gap:10,textAlign:"left",cursor:"pointer"}}><div style={{flex:1,minWidth:0}}><div style={{fontSize:11,fontWeight:700,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{j.description}</div><div style={{fontSize:10,color:med,marginTop:2}}>{j.entry_date}</div></div><div style={{textAlign:"right"}}><div style={{fontSize:11,fontWeight:800}}>{rp(j.total)}</div><div style={{fontSize:9,color:"#15803D",fontWeight:700,marginTop:2,display:"flex",justifyContent:"flex-end",alignItems:"center",gap:3}}><CheckCircle2 size={10}/>Selesai</div></div><ChevronDown size={15} style={{color:med,transform:open?"rotate(180deg)":"rotate(0deg)",transition:"transform .15s ease"}}/></button>{open?<div style={{padding:"0 13px 11px",background:"#FFFBF7"}}><div style={{fontSize:9,color:med,marginBottom:6}}>{j.reference||"Tanpa referensi"}</div>{(j.journal_lines??[]).map(l=><div key={l.id} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:8,fontSize:10,color:med,padding:"3px 0"}}><span>{l.accounting_accounts?.code} {l.accounting_accounts?.name}</span><span>{Number(l.debit)>0?`Debit ${rp(Number(l.debit))}`:`Kredit ${rp(Number(l.credit))}`}</span></div>)}</div>:null}</div>})}</div></section>
 </div>;
}
