"use client";
import {useEffect,useMemo,useState,useTransition} from "react";
import {AlertTriangle,CheckCircle2,Lock,Plus,Save,Trash2} from "lucide-react";
import {useAuth} from "@/lib/auth";
import {calculateCorporateTax} from "@/lib/pajak/pph-badan";
import {AccountingAccountRow,addFiscalAdjustment,CorporateTaxReturnRow,FiscalAdjustmentRow,isMissingTaxSchema,JournalEntryRow,loadFiscalWorkspace,removeFiscalAdjustment,saveCorporateTaxReturn} from "@/lib/pajak/store";

type Props={year:number;regime:string};
const ink="#3C2F2F",med="#7C685B",line="#E6D5BE",soft="#F6EEE6",accent="#A67B5B",green="#15803D";
const inp:React.CSSProperties={border:`1px solid ${line}`,borderRadius:7,padding:"7px 9px",fontSize:11,color:ink,background:"white",width:"100%"};
const rp=(v:number)=>`Rp ${Math.round(v).toLocaleString("id-ID")}`;

export default function FiscalCorporateTax({year,regime}:Props){
 const{user}=useAuth();const[accounts,setAccounts]=useState<AccountingAccountRow[]>([]),[journals,setJournals]=useState<JournalEntryRow[]>([]),[adjustments,setAdjustments]=useState<FiscalAdjustmentRow[]>([]),[savedReturn,setSavedReturn]=useState<CorporateTaxReturnRow|null>(null);
 const[credits,setCredits]=useState({pph22:0,pph23:0,pph25:0,other:0}),[direction,setDirection]=useState<"positive"|"negative">("positive"),[description,setDescription]=useState(""),[amount,setAmount]=useState(0),[message,setMessage]=useState(""),[schemaReady,setSchemaReady]=useState(true),[pending,startTransition]=useTransition();
 const locked=savedReturn?.status==="locked",unsupportedRegime=regime==="final_transition";
 const applyData=(d:Awaited<ReturnType<typeof loadFiscalWorkspace>>)=>{setAccounts(d.accounts);setJournals(d.journals.filter(j=>j.status==="locked"));setAdjustments(d.adjustments);setSavedReturn(d.taxReturn);if(d.taxReturn)setCredits({pph22:d.taxReturn.credit_pph22,pph23:d.taxReturn.credit_pph23,pph25:d.taxReturn.credit_pph25,other:d.taxReturn.credit_other});setSchemaReady(true)};
 useEffect(()=>{let cancel=false;loadFiscalWorkspace(year).then(d=>{if(!cancel)applyData(d)}).catch(e=>{if(!cancel){setSchemaReady(false);setMessage(isMissingTaxSchema(e)?"Jalankan migrasi rekonsiliasi fiskal terlebih dahulu.":"Gagal memuat data rekonsiliasi fiskal.")}});return()=>{cancel=true}},[year]);
 const accounting=useMemo(()=>{const lookup=new Map(accounts.map(a=>[a.id,a]));let turnover=0,revenue=0,expenses=0;for(const j of journals)for(const l of j.journal_lines??[]){const a=lookup.get(l.account_id);if(!a)continue;if(a.account_type==="revenue"){const n=Number(l.credit)-Number(l.debit);revenue+=n;if(a.code.startsWith("4"))turnover+=n}else if(a.account_type==="expense")expenses+=Number(l.debit)-Number(l.credit)}return{turnover,revenue,expenses,profit:revenue-expenses}},[accounts,journals]);
 const positive=adjustments.filter(a=>a.direction==="positive").reduce((s,a)=>s+Number(a.amount),0),negative=adjustments.filter(a=>a.direction==="negative").reduce((s,a)=>s+Number(a.amount),0);
 const result=calculateCorporateTax({turnover:accounting.turnover,commercialProfit:accounting.profit,positiveCorrections:positive,negativeCorrections:negative,credits});
 const addCorrection=()=>startTransition(async()=>{if(!schemaReady||locked)return;if(!description.trim()||amount<=0){setMessage("Isi keterangan dan nilai koreksi lebih dari nol.");return}try{const row=await addFiscalAdjustment({workspace:"toto",tax_year:year,direction,category:"",description,amount,legal_basis:"",is_temporary:false,created_by:user?.username??""});setAdjustments(current=>[row,...current]);setDescription("");setAmount(0);setMessage("Koreksi fiskal tersimpan.")}catch(e){setMessage(`Gagal menyimpan koreksi: ${(e as{message?:string}).message??"kesalahan database"}`)}});
 const removeCorrection=(id:string)=>startTransition(async()=>{if(locked||!window.confirm("Hapus koreksi fiskal ini?"))return;try{await removeFiscalAdjustment(id);setAdjustments(current=>current.filter(a=>a.id!==id))}catch(e){setMessage(`Gagal menghapus koreksi: ${(e as{message?:string}).message??"kesalahan database"}`)}});
 const save=(lock:boolean)=>startTransition(async()=>{if(!schemaReady||locked||unsupportedRegime)return;if(lock&&!window.confirm(`Kunci perhitungan PPh Badan ${year}? Koreksi fiskal tidak dapat diubah setelah dikunci.`))return;try{const row=await saveCorporateTaxReturn({workspace:"toto",tax_year:year,turnover:accounting.turnover,commercial_profit:accounting.profit,positive_corrections:positive,negative_corrections:negative,taxable_income:result.taxableIncome,facility_taxable_income:result.facilityTaxableIncome,standard_taxable_income:result.standardTaxableIncome,tax_due:result.taxDue,credit_pph22:credits.pph22,credit_pph23:credits.pph23,credit_pph25:credits.pph25,credit_other:credits.other,tax_balance:result.balance,status:lock?"locked":"draft",calculation_snapshot:{journal_count:journals.length,revenue:accounting.revenue,expenses:accounting.expenses,facility_rate:result.facilityRate,standard_rate:result.standardRate},created_by:user?.username??"",locked_by:lock?user?.username??"":null,locked_at:lock?new Date().toISOString():null});setSavedReturn(row);setMessage(lock?"PPh Badan berhasil dikunci.":"Draft PPh Badan tersimpan.")}catch(e){setMessage(`Gagal menyimpan: ${(e as{message?:string}).message??"kesalahan database"}`)}});

 return <div style={{display:"grid",gap:12}}>
  {message?<div style={{display:"flex",gap:7,padding:10,border:"1px solid #F3D08B",background:"#FFF9E8",borderRadius:8,fontSize:11,color:"#875F13"}}><AlertTriangle size={15}/>{message}</div>:null}
  {unsupportedRegime?<div style={{padding:10,border:"1px solid #F3D08B",background:"#FFF9E8",borderRadius:8,fontSize:11,color:"#875F13"}}>Profil badan menggunakan PPh Final masa transisi. Perhitungan tarif umum/Pasal 31E tidak dapat dikunci sampai rezim pajak dikonfirmasi.</div>:null}
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10}}>{[["Omzet usaha",accounting.turnover],["Laba komersial",accounting.profit],["Koreksi fiskal",positive-negative],["PPh terutang",result.taxDue]].map(([label,value])=><div key={String(label)} style={{background:"white",border:`1px solid ${line}`,borderRadius:9,padding:12}}><div style={{fontSize:10,color:med,fontWeight:700}}>{String(label)}</div><div style={{fontSize:15,fontWeight:800,marginTop:7,color:ink}}>{rp(Number(value))}</div></div>)}</div>
  <div className="grid grid-cols-1 xl:grid-cols-2" style={{gap:12,alignItems:"start"}}>
   <section style={{background:"white",border:`1px solid ${line}`,borderRadius:10,padding:13}}><h2 style={{fontSize:13,margin:"0 0 4px"}}>Rekonsiliasi fiskal</h2><p style={{fontSize:10,color:med,margin:"0 0 11px"}}>Laba diambil dari {journals.length} jurnal terkunci tahun {year}.</p><div style={{display:"grid",gridTemplateColumns:"130px 1fr 120px auto",gap:6,marginBottom:10}}><select disabled={locked} style={inp} value={direction} onChange={e=>setDirection(e.target.value as typeof direction)}><option value="positive">Koreksi +</option><option value="negative">Koreksi -</option></select><input disabled={locked} style={inp} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Contoh: biaya tidak dapat dikurangkan"/><input disabled={locked} type="number" min="0" style={{...inp,textAlign:"right"}} value={amount||""} onChange={e=>setAmount(Number(e.target.value))} placeholder="Nominal"/><button disabled={locked||pending} onClick={addCorrection} style={{border:0,borderRadius:7,background:accent,color:"white",padding:"0 9px",cursor:"pointer"}}><Plus size={15}/></button></div>{!adjustments.length?<div style={{fontSize:10,color:med,padding:"10px 0"}}>Belum ada koreksi fiskal.</div>:adjustments.map(a=><div key={a.id} style={{display:"grid",gridTemplateColumns:"1fr auto auto",gap:8,padding:"8px 0",borderBottom:`1px solid ${soft}`,alignItems:"center"}}><span style={{fontSize:11}}>{a.description}</span><b style={{fontSize:11,color:a.direction==="positive"?"#B91C1C":green}}>{a.direction==="positive"?"+":"-"}{rp(Number(a.amount))}</b>{!locked?<button onClick={()=>removeCorrection(a.id!)} style={{border:0,background:"transparent",color:"#B91C1C",cursor:"pointer"}}><Trash2 size={13}/></button>:<span/>}</div>)}</section>
   <section style={{background:"white",border:`1px solid ${line}`,borderRadius:10,padding:13}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:10}}><h2 style={{fontSize:13,margin:0}}>PPh Badan {year}</h2>{locked?<span style={{fontSize:10,color:green,fontWeight:700,display:"flex",gap:4}}><CheckCircle2 size={13}/>Terkunci</span>:null}</div>{[["Laba komersial",accounting.profit],["Koreksi positif",positive],["Koreksi negatif",-negative],["Penghasilan kena pajak",result.taxableIncome],["PKP fasilitas Pasal 31E (11%)",result.facilityTaxableIncome],["PKP tarif umum (22%)",result.standardTaxableIncome],["PPh terutang",result.taxDue]].map(([label,value])=><div key={String(label)} style={{display:"flex",justifyContent:"space-between",gap:8,padding:"6px 0",borderBottom:`1px solid ${soft}`,fontSize:10}}><span style={{color:med}}>{String(label)}</span><b>{rp(Number(value))}</b></div>)}<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:11}}>{([["pph22","Kredit PPh 22"],["pph23","Kredit PPh 23"],["pph25","Angsuran PPh 25"],["other","Kredit lainnya"]] as const).map(([key,label])=><label key={key} style={{fontSize:10,color:med,fontWeight:700}}>{label}<input disabled={locked} type="number" min="0" value={credits[key]||""} onChange={e=>setCredits({...credits,[key]:Number(e.target.value)})} style={{...inp,marginTop:4,textAlign:"right"}}/></label>)}</div><div style={{display:"flex",justifyContent:"space-between",padding:"11px 0",marginTop:8,fontSize:12,fontWeight:800}}><span>{result.balance>=0?"Kurang bayar":"Lebih bayar"}</span><span style={{color:result.balance>0?"#B91C1C":green}}>{rp(Math.abs(result.balance))}</span></div>{!locked?<div style={{display:"flex",justifyContent:"flex-end",gap:7}}><button disabled={pending||unsupportedRegime} onClick={()=>save(false)} style={{border:`1px solid ${line}`,background:"white",borderRadius:7,padding:"8px 10px",fontSize:10,fontWeight:700,display:"flex",gap:5}}><Save size={12}/>Simpan draft</button><button disabled={pending||unsupportedRegime} onClick={()=>save(true)} style={{border:0,background:accent,color:"white",borderRadius:7,padding:"8px 10px",fontSize:10,fontWeight:700,display:"flex",gap:5}}><Lock size={12}/>Kunci tahun</button></div>:null}</section>
  </div>
 </div>;
}
