"use client";
import{useEffect,useMemo,useState}from"react";
import{AlertTriangle,CheckCircle2,Clock3,Database,FileCheck2,Users}from"lucide-react";
import{useStore}from"@/lib/store";
import{loadTaxMonitoring}from"@/lib/pajak/store";

type Props={year:number;month:number;isPkp:boolean;employeeConfigured:number;employeeTotal:number};
const med="#7C685B",line="#E6D5BE",soft="#F6EEE6",green="#15803D";
export default function TaxDashboard({year,month,isPkp,employeeConfigured,employeeTotal}:Props){
 const{cashFlow}=useStore();const[data,setData]=useState<Awaited<ReturnType<typeof loadTaxMonitoring>>|null>(null),[error,setError]=useState("");const period=`${year}-${String(month).padStart(2,"0")}`;
 useEffect(()=>{let cancel=false;loadTaxMonitoring(year,month).then(d=>{if(!cancel)setData(d)}).catch(()=>{if(!cancel)setError("Data monitoring belum dapat dimuat.")});return()=>{cancel=true}},[year,month]);
 const status=useMemo(()=>{if(!data)return null;const finance=cashFlow.filter(c=>!c.isTest&&!c.transferGroup&&c.date.startsWith(period)),taxSources=new Set(data.transactions.map(t=>t.source_id).filter(Boolean)),journalSources=new Set(data.journals.filter(j=>j.source_type==="cash_flow").map(j=>j.source_id).filter(Boolean)),taxPending=finance.filter(c=>!taxSources.has(c.id)).length,journalPending=finance.filter(c=>!c.isAdjustment&&!journalSources.has(c.id)).length,payrollLocked=data.payroll.length>0&&data.payroll.every(p=>p.status==="locked"),requiredCodes=isPkp?["pph21","pph23","ppn"]:["pph21","pph23"],compliancePending=requiredCodes.filter(code=>{const c=data.compliance.find(x=>x.tax_code===code);return!c||c.payment_status==="pending"||c.filing_status==="pending"}).length;return{taxPending,journalPending,payrollLocked,compliancePending,taxReturnLocked:data.taxReturn?.status==="locked"}},[data,cashFlow,period,isPkp]);
 if(error)return <div style={{padding:10,border:"1px solid #F3D08B",background:"#FFF9E8",borderRadius:8,fontSize:10,color:"#875F13"}}>{error}</div>;
 if(!status)return <div style={{padding:14,border:`1px solid ${line}`,background:"white",borderRadius:9,fontSize:10,color:med}}>Memuat ringkasan pajak...</div>;
 const items=[{icon:Database,label:"Review transaksi",value:status.taxPending?`${status.taxPending} belum review`:"Selesai",ok:status.taxPending===0},{icon:FileCheck2,label:"Jurnal Keuangan",value:status.journalPending?`${status.journalPending} belum masuk`:"Tersinkron",ok:status.journalPending===0},{icon:Users,label:"Profil & PPh 21",value:employeeConfigured<employeeTotal?`${employeeTotal-employeeConfigured} profil belum lengkap`:status.payrollLocked?"Masa terkunci":"Belum dikunci",ok:employeeConfigured===employeeTotal&&status.payrollLocked},{icon:Clock3,label:"Bayar & lapor",value:status.compliancePending?`${status.compliancePending} perlu tindakan`:"Lengkap",ok:status.compliancePending===0}];
 return <><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:10,marginBottom:12}}>{items.map(({icon:Icon,label,value,ok})=><div key={label} style={{background:"white",border:`1px solid ${line}`,borderRadius:9,padding:12}}><div style={{display:"flex",alignItems:"center",gap:6,fontSize:10,color:med,fontWeight:700}}><Icon size={14}/>{label}</div><div style={{display:"flex",alignItems:"center",gap:5,fontSize:13,fontWeight:800,marginTop:8,color:ok?green:"#B45309"}}>{ok?<CheckCircle2 size={14}/>:<AlertTriangle size={14}/>} {value}</div></div>)}</div><div style={{padding:"9px 11px",background:soft,borderRadius:8,fontSize:10,color:med}}>Status tahun {year}: PPh Badan {status.taxReturnLocked?"sudah dikunci":"belum dikunci"}. Ringkasan ini mengikuti masa {period}.</div></>;
}
