"use client";
import{useEffect,useMemo,useState,useTransition}from"react";
import{AlertTriangle,Clock3,Save}from"lucide-react";
import{useAuth}from"@/lib/auth";
import{useKaryawan}from"@/lib/karyawan-store";
import{useStore}from"@/lib/store";
import{reconcileValues,taxDeadlines}from"@/lib/pajak/reconciliation";
import{AccountingAccountRow,isMissingTaxSchema,JournalEntryRow,loadTaxMonitoring,PayrollTaxPeriodRow,saveTaxCompliance,TaxComplianceRow,TaxTransactionRow}from"@/lib/pajak/store";

type Props={year:number;month:number;isPkp:boolean};
const ink="#3C2F2F",med="#7C685B",line="#E6D5BE",soft="#F6EEE6",accent="#A67B5B",green="#15803D";
const inp:React.CSSProperties={border:`1px solid ${line}`,borderRadius:6,padding:"6px 8px",fontSize:10,color:ink,background:"white",width:"100%"};
const rp=(v:number)=>`Rp ${Math.round(v).toLocaleString("id-ID")}`;
const periodDate=(r:{tanggal_gajian?:string;periode_selesai?:string;periode:string})=>r.tanggal_gajian||r.periode_selesai||r.periode.match(/~(\d{4}-\d{2}-\d{2})$/)?.[1]||`${r.periode.slice(0,7)}-01`;

export default function TaxReconciliationCompliance({year,month,isPkp}:Props){
 const{user}=useAuth(),{gaji}=useKaryawan(),{cashFlow}=useStore();const[accounts,setAccounts]=useState<AccountingAccountRow[]>([]),[journals,setJournals]=useState<JournalEntryRow[]>([]),[transactions,setTransactions]=useState<TaxTransactionRow[]>([]),[payroll,setPayroll]=useState<PayrollTaxPeriodRow[]>([]),[compliance,setCompliance]=useState<TaxComplianceRow[]>([]),[message,setMessage]=useState(""),[pending,startTransition]=useTransition();
 const period=`${year}-${String(month).padStart(2,"0")}`;
 const apply=(d:Awaited<ReturnType<typeof loadTaxMonitoring>>)=>{setAccounts(d.accounts);setJournals(d.journals);setTransactions(d.transactions);setPayroll(d.payroll);setCompliance(d.compliance)};
 useEffect(()=>{let cancel=false;loadTaxMonitoring(year,month).then(d=>{if(!cancel)apply(d)}).catch(e=>{if(!cancel)setMessage(isMissingTaxSchema(e)?"Jalankan migrasi checklist kepatuhan terlebih dahulu.":"Gagal memuat data ekualisasi.")});return()=>{cancel=true}},[year,month]);
 const values=useMemo(()=>{const accountMap=new Map(accounts.map(a=>[a.id,a]));let journalSales=0;for(const j of journals.filter(j=>j.status==="locked"))for(const l of j.journal_lines??[]){const a=accountMap.get(l.account_id);if(a?.code==="4101")journalSales+=Number(l.credit)-Number(l.debit)}
  const ppn=transactions.filter(t=>t.tax_code==="ppn"),ppnDpp=ppn.filter(t=>t.tax_direction==="output").reduce((s,t)=>s+Number(t.dpp_amount),0),ppnOutput=ppn.filter(t=>t.tax_direction==="output").reduce((s,t)=>s+Number(t.tax_amount),0),ppnInput=ppn.filter(t=>t.tax_direction==="input").reduce((s,t)=>s+Number(t.tax_amount),0);
  const payrollActual=gaji.filter(r=>periodDate(r).startsWith(period)).reduce((s,r)=>s+r.gaji_pokok+r.lembur+r.tunjangan,0),payrollTaxBase=payroll.reduce((s,r)=>s+Number(r.gross_income),0),pph21=payroll.reduce((s,r)=>s+Number(r.tax_withheld),0);
  const serviceRx=/jasa|service|servis|sewa|konsultan|desain|perawatan|bengkel|ongkir|ekspedisi/i,serviceSource=cashFlow.filter(c=>!c.isTest&&!c.transferGroup&&c.type==="expense"&&c.date.startsWith(period)&&serviceRx.test(`${c.category} ${c.description}`)).reduce((s,c)=>s+c.amount,0),pph23Rows=transactions.filter(t=>t.tax_code==="pph23"),pph23Dpp=pph23Rows.reduce((s,t)=>s+Number(t.dpp_amount),0),pph23=pph23Rows.reduce((s,t)=>s+Number(t.tax_amount),0);
  return{journalSales,ppnDpp,ppnOutput,ppnInput,payrollActual,payrollTaxBase,pph21,serviceSource,pph23Dpp,pph23}},[accounts,journals,transactions,payroll,gaji,cashFlow,period]);
 const checks=[{code:"ppn",label:"Omzet vs DPP PPN",source:values.journalSales,reported:values.ppnDpp,applicable:isPkp},{code:"pph21",label:"Gaji vs bruto PPh 21",source:values.payrollActual,reported:values.payrollTaxBase,applicable:true},{code:"pph23",label:"Indikasi jasa vs DPP PPh 23",source:values.serviceSource,reported:values.pph23Dpp,applicable:true}] as const;
 const amounts={ppn:Math.max(0,values.ppnOutput-values.ppnInput),pph21:values.pph21,pph23:values.pph23};
 const rowOf=(code:"ppn"|"pph21"|"pph23")=>{const existing=compliance.find(r=>r.tax_code===code),due=taxDeadlines(year,month,code);return existing??{workspace:"toto",tax_period:period,tax_code:code,amount:amounts[code],payment_due_date:due.payment,filing_due_date:due.filing,payment_status:code==="ppn"&&!isPkp?"not_applicable":"pending",filing_status:code==="ppn"&&!isPkp?"not_applicable":"pending",payment_reference:"",filing_reference:"",notes:"",updated_by:user?.username??""} as TaxComplianceRow};
 const updateLocal=(code:"ppn"|"pph21"|"pph23",patch:Partial<TaxComplianceRow>)=>setCompliance(current=>[...current.filter(r=>r.tax_code!==code),{...rowOf(code),...patch}]);
 const saveRow=(code:"ppn"|"pph21"|"pph23")=>startTransition(async()=>{try{const base=rowOf(code),row=await saveTaxCompliance({...base,amount:amounts[code],updated_by:user?.username??"",paid_at:base.payment_status==="paid"?base.paid_at??new Date().toISOString():null,filed_at:base.filing_status==="filed"?base.filed_at??new Date().toISOString():null});setCompliance(current=>[...current.filter(r=>r.tax_code!==code),row]);setMessage(`${code.toUpperCase()} tersimpan.`)}catch(e){setMessage(`Gagal menyimpan: ${(e as{message?:string}).message??"kesalahan database"}`)}});
 const today=new Date().toISOString().slice(0,10);
 return <div style={{display:"grid",gap:12}}>
  {message?<div role="status" style={{padding:9,border:"1px solid #F3D08B",background:"#FFF9E8",borderRadius:7,fontSize:10,color:"#875F13",display:"flex",gap:6}}><AlertTriangle size={14}/>{message}</div>:null}
  <section style={{background:"white",border:`1px solid ${line}`,borderRadius:10,overflow:"hidden"}}><div style={{padding:"12px 14px",borderBottom:`1px solid ${line}`}}><h2 style={{fontSize:14,margin:0}}>Ekualisasi masa {period}</h2><p style={{fontSize:10,color:med,margin:"3px 0 0"}}>Selisih menandai data yang perlu diperiksa, bukan kesalahan otomatis.</p></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:690,fontSize:10}}><thead><tr style={{background:"#EDE0D4"}}>{["Pemeriksaan","Sumber ERP","Data pajak","Selisih","Status"].map(h=><th key={h} style={{padding:"8px 10px",textAlign:h==="Pemeriksaan"||h==="Status"?"left":"right"}}>{h}</th>)}</tr></thead><tbody>{checks.map(c=>{const r=reconcileValues(c.source,c.reported,c.applicable);return <tr key={c.code} style={{borderBottom:`1px solid ${soft}`}}><td style={{padding:"9px 10px",fontWeight:700}}>{c.label}</td><td style={{padding:"9px 10px",textAlign:"right"}}>{rp(c.source)}</td><td style={{padding:"9px 10px",textAlign:"right"}}>{rp(c.reported)}</td><td style={{padding:"9px 10px",textAlign:"right",fontWeight:700,color:r.status==="difference"?"#B91C1C":green}}>{rp(r.difference)}</td><td style={{padding:"9px 10px"}}><span style={{color:r.status==="match"?green:r.status==="difference"?"#B91C1C":med,fontWeight:700}}>{r.status==="match"?"Cocok":r.status==="difference"?"Perlu review":r.status==="not_applicable"?"Tidak berlaku":"Belum ada data"}</span></td></tr>})}</tbody></table></div></section>
  <section style={{background:"white",border:`1px solid ${line}`,borderRadius:10,overflow:"hidden"}}><div style={{padding:"12px 14px",borderBottom:`1px solid ${line}`}}><h2 style={{fontSize:14,margin:0}}>Pembayaran & pelaporan</h2><p style={{fontSize:10,color:med,margin:"3px 0 0"}}>Tanggal dapat disesuaikan jika ada relaksasi atau ketentuan khusus.</p></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:980,fontSize:10}}><thead><tr style={{background:"#EDE0D4"}}>{["Pajak","Nilai","Batas bayar","Status bayar","Batas lapor","Status lapor","Referensi",""].map(h=><th key={h} style={{padding:"8px",textAlign:h==="Nilai"?"right":"left"}}>{h}</th>)}</tr></thead><tbody>{(["pph21","pph23","ppn"] as const).map(code=>{const r=rowOf(code),overduePay=r.payment_status==="pending"&&!!r.payment_due_date&&r.payment_due_date<today,overdueFile=r.filing_status==="pending"&&!!r.filing_due_date&&r.filing_due_date<today;return <tr key={code} style={{borderBottom:`1px solid ${soft}`}}><td style={{padding:8,fontWeight:800,textTransform:"uppercase"}}>{code}</td><td style={{padding:8,textAlign:"right",fontWeight:700}}>{rp(amounts[code])}</td><td style={{padding:6}}><input type="date" style={inp} value={r.payment_due_date??""} onChange={e=>updateLocal(code,{payment_due_date:e.target.value})}/>{overduePay?<small style={{color:"#B91C1C"}}>Terlambat</small>:null}</td><td style={{padding:6}}><select style={inp} value={r.payment_status} onChange={e=>updateLocal(code,{payment_status:e.target.value as TaxComplianceRow["payment_status"]})}><option value="pending">Belum bayar</option><option value="paid">Sudah bayar</option><option value="not_applicable">Tidak berlaku</option></select></td><td style={{padding:6}}><input type="date" style={inp} value={r.filing_due_date??""} onChange={e=>updateLocal(code,{filing_due_date:e.target.value})}/>{overdueFile?<small style={{color:"#B91C1C"}}>Terlambat</small>:null}</td><td style={{padding:6}}><select style={inp} value={r.filing_status} onChange={e=>updateLocal(code,{filing_status:e.target.value as TaxComplianceRow["filing_status"]})}><option value="pending">Belum lapor</option><option value="filed">Sudah lapor</option><option value="not_applicable">Tidak berlaku</option></select></td><td style={{padding:6}}><input style={{...inp,minWidth:130}} value={r.payment_reference} onChange={e=>updateLocal(code,{payment_reference:e.target.value})} placeholder="NTPN / referensi"/></td><td style={{padding:6}}><button disabled={pending} onClick={()=>saveRow(code)} title="Simpan status" style={{border:0,borderRadius:6,background:accent,color:"white",padding:7,cursor:"pointer"}}><Save size={13}/></button></td></tr>})}</tbody></table></div><div style={{padding:"8px 12px",fontSize:9,color:med,display:"flex",gap:5,alignItems:"center"}}><Clock3 size={12}/>Tanggal standar sistem: PPh bayar tanggal 15 dan lapor tanggal 20 bulan berikutnya; PPN akhir bulan berikutnya.</div></section>
 </div>;
}
