"use client";

import { useEffect, useMemo, useState, useTransition } from "react";
import { AlertTriangle, BookOpen, FileSpreadsheet, Printer, Scale } from "lucide-react";
import {
  AccountingAccountRow, CorporateTaxReturnRow, FiscalAdjustmentRow, isMissingTaxSchema,
  JournalEntryRow, loadTaxYearReports, PayrollTaxPeriodRow, ReportBankAccountRow,
  ReportPayableRow, ReportReceivableRow, TaxComplianceRow, TaxTransactionRow,
} from "@/lib/pajak/store";
import type { SalesHppRecognitionRow } from "@/lib/hpp/store";
import { buildAccountingReport, buildGeneralLedger, StatementRow } from "@/lib/pajak/financial-reports";
import { parseIdNum } from "@/lib/utils";

type Props={year:number;month:number;entityName:string;npwp:string};
type View="summary"|"profit"|"position"|"cash"|"trial"|"ledger"|"subledger";
type Data={accounts:AccountingAccountRow[];journals:JournalEntryRow[];payroll:PayrollTaxPeriodRow[];transactions:TaxTransactionRow[];compliance:TaxComplianceRow[];adjustments:FiscalAdjustmentRow[];taxReturn:CorporateTaxReturnRow|null;salesHpp:SalesHppRecognitionRow[];receivables:ReportReceivableRow[];payables:ReportPayableRow[];banks:ReportBankAccountRow[];accountingPeriod:{status:"open"|"review"|"closed"}|null};
const c={ink:"#3C2F2F",med:"#7C685B",line:"#E6D5BE",soft:"#F6EEE6",accent:"#A67B5B",green:"#15803D",amber:"#9A6700",red:"#B91C1C",paper:"#FFFBF7"};
const rp=(value:number)=>`Rp ${Math.round(value).toLocaleString("id-ID")}`;
const MONTHS=["Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember"];
const ageDays=(date:string)=>{const time=new Date(date).getTime();return Number.isFinite(time)?Math.max(0,Math.floor((Date.now()-time)/86400000)):0};
const ageBucket=(days:number)=>days<=30?"0–30":days<=60?"31–60":days<=90?"61–90":">90";

function StatementSection({title,rows,totalLabel,totalValue}:{title:string;rows:StatementRow[];totalLabel?:string;totalValue?:number}){
 return <div style={{borderBottom:`1px solid ${c.line}`,padding:"11px 13px"}}><div style={{fontSize:10,fontWeight:800,color:c.med,marginBottom:6}}>{title}</div>{rows.length?rows.map(row=><div key={row.id} style={{display:"grid",gridTemplateColumns:"62px minmax(160px,1fr) auto",gap:8,padding:"4px 0",fontSize:10}}><span style={{color:c.med}}>{row.code}</span><span>{row.name}</span><b style={{fontVariantNumeric:"tabular-nums"}}>{rp(row.amount)}</b></div>):<div style={{fontSize:9,color:c.med,padding:"3px 0"}}>Belum ada saldo.</div>}{totalLabel?<div style={{display:"flex",justifyContent:"space-between",gap:10,marginTop:7,paddingTop:7,borderTop:`1px solid ${c.soft}`,fontSize:10,fontWeight:800}}><span>{totalLabel}</span><span>{rp(totalValue??0)}</span></div>:null}</div>;
}

export default function TaxReports({year,month,entityName,npwp}:Props){
 const[data,setData]=useState<Data|null>(null),[view,setView]=useState<View>("summary"),[message,setMessage]=useState(""),[ledgerAccount,setLedgerAccount]=useState(""),[pending,startTransition]=useTransition();
 const start=`${year}-${String(month).padStart(2,"0")}-01`,end=new Date(year,month,0).toISOString().slice(0,10),period=`${year}-${String(month).padStart(2,"0")}`;
 useEffect(()=>{let active=true;loadTaxYearReports(year,month).then(result=>{if(active)setData(result as Data)}).catch(error=>{if(active)setMessage(isMissingTaxSchema(error)?"Jalankan migration laporan akuntansi agar seluruh laporan dapat digunakan.":`Gagal memuat laporan: ${(error as{message?:string}).message??"kesalahan database"}`)});return()=>{active=false}},[year,month]);
 const report=useMemo(()=>data?buildAccountingReport(data.accounts,data.journals,year,month):null,[data,year,month]);
 const receivables=useMemo(()=>{if(!data)return[];const map=new Map<string,{invoice:string;customer:string;date:string;amount:number}>();for(const row of data.receivables){const amount=parseIdNum(row.harga??"")*parseIdNum(row.ukuran??"")*parseIdNum(row.qty??"");if(amount<=0)continue;const key=(row.no_inv||String(row.id)).trim(),old=map.get(key);if(old)old.amount+=amount;else map.set(key,{invoice:key,customer:(row.customer||"").trim(),date:(row.tanggal||"").slice(0,10),amount})}return[...map.values()].map(row=>({...row,days:ageDays(row.date),bucket:ageBucket(ageDays(row.date))})).sort((a,b)=>b.days-a.days)},[data]);
 const payables=useMemo(()=>data?.payables.map(row=>({invoice:row.no_invoice||row.id,supplier:row.supplier,date:row.tanggal.slice(0,10),amount:Math.max(0,Number(row.grand_total)-Number(row.paid_amount)),days:ageDays(row.tanggal),bucket:ageBucket(ageDays(row.tanggal))})).filter(row=>row.amount>0).sort((a,b)=>b.days-a.days)??[],[data]);
 const ledger=useMemo(()=>data?buildGeneralLedger(data.accounts,data.journals,ledgerAccount,start,end):null,[data,ledgerAccount,start,end]);
 if(!data||!report)return <div style={{padding:18,border:`1px solid ${c.line}`,background:"white",borderRadius:9,fontSize:11,color:c.med}}>{message||"Memuat laporan akuntansi..."}</div>;
 const income=report.incomeStatement,balance=report.balanceSheet;
 const arOperational=receivables.reduce((value,row)=>value+row.amount,0),apOperational=payables.reduce((value,row)=>value+row.amount,0);
 const arJournal=report.trialBalance.find(row=>row.code==="1201")?.closing??0,apJournal=report.trialBalance.find(row=>row.code==="2101")?.closing??0;
 const operationalCash=data.banks.reduce((value,row)=>value+Number(row.balance),0),cashJournal=balance.currentAssets.filter(row=>/^110[12]$/.test(row.code)).reduce((value,row)=>value+row.amount,0);
 const exportExcel=()=>startTransition(async()=>{const XLSX=await import("xlsx"),book=XLSX.utils.book_new(),add=(name:string,rows:Record<string,unknown>[])=>XLSX.utils.book_append_sheet(book,XLSX.utils.json_to_sheet(rows),name.slice(0,31));
  add("Ringkasan",[{Periode:period,Pendapatan:income.netRevenue,HPP:income.totalCogs,Laba_Kotor:income.grossProfit,Beban_Operasional:income.totalOperatingExpenses,Laba_Bersih:income.netProfit,Aset:balance.totalAssets,Liabilitas:balance.totalLiabilities,Ekuitas:balance.totalEquity,Selisih_Neraca:balance.difference,Arus_Kas_Bersih:report.cashFlow.netChange,Piutang_Operasional:arOperational,Utang_Operasional:apOperational}]);
  add("Laba Rugi",[...income.mainRevenue,...income.salesReturns,...income.cogs,...income.operatingExpenses,...income.otherIncome,...income.otherExpenses,...income.taxExpenses].map(row=>({Kode:row.code,Akun:row.name,Nilai:row.amount})));
  add("Posisi Keuangan",[...balance.currentAssets,...balance.nonCurrentAssets,...balance.contraAssets,...balance.currentLiabilities,...balance.nonCurrentLiabilities,...balance.equity,{id:"prior",code:"",name:"Akumulasi laba periode sebelumnya",amount:balance.priorUnclosedEarnings},{id:"current",code:"",name:"Laba tahun berjalan",amount:balance.currentEarnings}].map(row=>({Kode:row.code,Akun:row.name,Nilai:row.amount})));
  add("Neraca Saldo",report.trialBalance.map(row=>({Kode:row.code,Akun:row.name,Saldo_Awal:row.opening,Debit:row.periodDebit,Kredit:row.periodCredit,Saldo_Debit:row.closingDebit,Saldo_Kredit:row.closingCredit})));
  add("Arus Kas",report.cashFlow.rows.map(row=>({Tanggal:row.date,Referensi:row.reference,Keterangan:row.description,Klasifikasi:row.classification,Nilai:row.amount})));
  add("Bulanan",report.monthly.map(row=>({Bulan:MONTHS[row.month-1],Pendapatan:row.revenue,HPP:row.cogs,Laba_Kotor:row.grossProfit,Beban_Operasional:row.operatingExpenses,Laba_Bersih:row.netProfit})));
  add("Jurnal",data.journals.filter(j=>j.entry_date>=start&&j.entry_date<=end).flatMap(j=>(j.journal_lines??[]).map(line=>({Tanggal:j.entry_date,Referensi:j.reference,Sumber:j.source_type,Keterangan:j.description,Akun:`${line.accounting_accounts?.code??""} ${line.accounting_accounts?.name??""}`,Debit:Number(line.debit),Kredit:Number(line.credit),Status:j.status}))));
  add("Piutang",receivables.map(row=>({Invoice:row.invoice,Pelanggan:row.customer,Tanggal:row.date,Umur_Hari:row.days,Kelompok:row.bucket,Sisa:row.amount})));
  add("Utang",payables.map(row=>({Invoice:row.invoice,Supplier:row.supplier,Tanggal:row.date,Umur_Hari:row.days,Kelompok:row.bucket,Sisa:row.amount})));
  add("Pajak",data.transactions.map(row=>({Tanggal:row.transaction_date,Jenis:row.tax_code,DPP:row.dpp_amount,Pajak:row.tax_amount,Dokumen:row.document_number,Status:row.status})));
  XLSX.writeFile(book,`laporan-keuangan-${period}.xlsx`);setMessage("Paket laporan Excel berhasil dibuat.")});
 const exportPdf=()=>startTransition(async()=>{const[{jsPDF},{default:autoTable}]=await Promise.all([import("jspdf"),import("jspdf-autotable")]),doc=new jsPDF({unit:"mm",format:"a4"});const heading=(title:string,subtitle:string)=>{doc.setFontSize(15);doc.setTextColor(60,47,47);doc.text(title,14,16);doc.setFontSize(8);doc.setTextColor(124,104,91);doc.text(subtitle,14,22)};heading("LAPORAN KEUANGAN",`${entityName} | ${period} | NPWP ${npwp||"-"}`);autoTable(doc,{startY:28,head:[["Ringkasan","Nilai"]],body:[["Pendapatan",rp(income.netRevenue)],["Laba kotor",rp(income.grossProfit)],["Laba bersih",rp(income.netProfit)],["Total aset",rp(balance.totalAssets)],["Total liabilitas",rp(balance.totalLiabilities)],["Total ekuitas",rp(balance.totalEquity)],["Arus kas bersih",rp(report.cashFlow.netChange)]],styles:{fontSize:8},headStyles:{fillColor:[166,123,91]}});
  doc.addPage();heading("LAPORAN LABA RUGI",`${entityName} | ${start} sampai ${end}`);autoTable(doc,{startY:28,head:[["Kode","Akun","Nilai"]],body:[...income.mainRevenue,...income.salesReturns,...income.cogs,...income.operatingExpenses,...income.otherIncome,...income.otherExpenses,...income.taxExpenses].map(row=>[row.code,row.name,rp(row.amount)]),styles:{fontSize:7},headStyles:{fillColor:[166,123,91]},columnStyles:{2:{halign:"right"}}});
  doc.addPage();heading("LAPORAN POSISI KEUANGAN",`${entityName} | per ${end}`);autoTable(doc,{startY:28,head:[["Kode","Akun","Nilai"]],body:[...balance.currentAssets,...balance.nonCurrentAssets,...balance.contraAssets,...balance.currentLiabilities,...balance.nonCurrentLiabilities,...balance.equity,{id:"prior",code:"",name:"Akumulasi laba periode sebelumnya",amount:balance.priorUnclosedEarnings},{id:"current",code:"",name:"Laba tahun berjalan",amount:balance.currentEarnings}].map(row=>[row.code,row.name,rp(row.amount)]),styles:{fontSize:7},headStyles:{fillColor:[166,123,91]},columnStyles:{2:{halign:"right"}}});
  doc.addPage();heading("LAPORAN ARUS KAS",`${entityName} | ${start} sampai ${end}`);autoTable(doc,{startY:28,head:[["Tanggal","Referensi","Keterangan","Klasifikasi","Nilai"]],body:report.cashFlow.rows.map(row=>[row.date,row.reference,row.description,row.classification,rp(row.amount)]),styles:{fontSize:6.5},headStyles:{fillColor:[166,123,91]},columnStyles:{4:{halign:"right"}}});
  doc.addPage();heading("LAPORAN PERUBAHAN EKUITAS",`${entityName} | sampai ${end}`);autoTable(doc,{startY:28,head:[["Komponen","Nilai"]],body:[["Saldo awal",rp(report.equity.opening)],["Setoran modal",rp(report.equity.ownerContributions)],["Prive owner",rp(-report.equity.drawings)],["Laba tahun berjalan",rp(report.equity.currentProfit)],["Saldo akhir",rp(report.equity.closing)]],styles:{fontSize:8},headStyles:{fillColor:[166,123,91]},columnStyles:{1:{halign:"right"}}});
  doc.addPage();heading("NERACA SALDO",`${entityName} | ${start} sampai ${end}`);autoTable(doc,{startY:28,head:[["Kode","Akun","Saldo awal","Debit","Kredit","Saldo debit","Saldo kredit"]],body:report.trialBalance.map(row=>[row.code,row.name,rp(row.opening),rp(row.periodDebit),rp(row.periodCredit),rp(row.closingDebit),rp(row.closingCredit)]),styles:{fontSize:5.8},headStyles:{fillColor:[166,123,91]},columnStyles:{2:{halign:"right"},3:{halign:"right"},4:{halign:"right"},5:{halign:"right"},6:{halign:"right"}}});doc.setFontSize(7);doc.setTextColor(124,104,91);doc.text("Laporan internal berbasis jurnal terkunci. Verifikasi sebelum digunakan sebagai laporan final.",14,290);doc.save(`laporan-keuangan-${period}.pdf`);setMessage("Paket laporan PDF berhasil dibuat.")});
 const tabs:Array<[View,string]>=[["summary","Ringkasan"],["profit","Laba rugi"],["position","Posisi keuangan"],["cash","Arus kas & ekuitas"],["trial","Neraca saldo"],["ledger","Buku besar"],["subledger","Piutang & utang"]];
 return <div style={{display:"grid",gap:12}}>
  {message?<div role="status" style={{display:"flex",gap:7,padding:9,border:"1px solid #F3D08B",background:"#FFF9E8",borderRadius:7,fontSize:10,color:"#875F13"}}><AlertTriangle size={14}/><span style={{flex:1}}>{message}</span><button onClick={()=>setMessage("")} style={{border:0,background:"transparent",fontWeight:700,color:"inherit",cursor:"pointer"}}>Tutup</button></div>:null}
  <section style={{background:"white",border:`1px solid ${c.line}`,borderRadius:10,overflow:"hidden"}}><div style={{padding:"12px 14px",display:"flex",alignItems:"center",gap:10,flexWrap:"wrap"}}><div><h2 style={{fontSize:14,margin:0}}>Laporan keuangan {MONTHS[month-1]} {year}</h2><p style={{fontSize:9,color:c.med,margin:"4px 0 0"}}>Basis akrual · jurnal terkunci · periode {data.accountingPeriod?.status==="closed"?"ditutup":data.accountingPeriod?.status==="review"?"review":"terbuka"}</p></div><div style={{marginLeft:"auto",display:"flex",gap:7}}><button disabled={pending} onClick={exportExcel} style={{border:`1px solid ${c.line}`,background:"white",borderRadius:7,padding:"8px 10px",fontSize:10,fontWeight:700,display:"flex",gap:5,cursor:"pointer"}}><FileSpreadsheet size={13}/>Excel lengkap</button><button disabled={pending} onClick={exportPdf} style={{border:0,background:c.accent,color:"white",borderRadius:7,padding:"8px 10px",fontSize:10,fontWeight:700,display:"flex",gap:5,cursor:"pointer"}}><Printer size={13}/>PDF laporan</button></div></div><nav aria-label="Jenis laporan" style={{display:"flex",gap:3,padding:"0 8px",overflowX:"auto",borderTop:`1px solid ${c.soft}`}}>{tabs.map(([key,label])=><button key={key} onClick={()=>setView(key)} style={{border:0,borderBottom:view===key?`2px solid ${c.accent}`:"2px solid transparent",background:"transparent",padding:"9px 8px",fontSize:9,fontWeight:800,color:view===key?c.ink:c.med,whiteSpace:"nowrap",cursor:"pointer"}}>{label}</button>)}</nav></section>
  {report.diagnostics.draftJournals||report.diagnostics.unbalancedJournals.length||report.diagnostics.missingAccountLines?<div style={{padding:10,border:"1px solid #F3D08B",background:"#FFF9E8",borderRadius:8,fontSize:9,color:c.amber}}>Pemeriksaan jurnal: {report.diagnostics.draftJournals} draft · {report.diagnostics.unbalancedJournals.length} tidak seimbang · {report.diagnostics.missingAccountLines} baris tanpa akun.</div>:null}
  {view==="summary"?<Summary report={report} operational={{cash:operationalCash,ar:arOperational,ap:apOperational}} journal={{cash:cashJournal,ar:arJournal,ap:apJournal}}/>:null}
  {view==="profit"?<ProfitStatement income={income} salesHpp={data.salesHpp}/>:null}
  {view==="position"?<PositionStatement balance={balance}/>:null}
  {view==="cash"?<CashAndEquity report={report}/>:null}
  {view==="trial"?<TrialBalance report={report}/>:null}
  {view==="ledger"?<GeneralLedger data={data} ledgerAccount={ledgerAccount} setLedgerAccount={setLedgerAccount} ledger={ledger}/>:null}
  {view==="subledger"?<Subledgers receivables={receivables} payables={payables} journal={{ar:arJournal,ap:apJournal}}/>:null}
 </div>;
}

type Report=ReturnType<typeof buildAccountingReport>;
function Summary({report,operational,journal}:{report:Report;operational:{cash:number;ar:number;ap:number};journal:{cash:number;ar:number;ap:number}}){const i=report.incomeStatement,b=report.balanceSheet;return <><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(165px,1fr))",gap:8}}>{[["Pendapatan",i.netRevenue],["Laba kotor",i.grossProfit],["Laba bersih",i.netProfit],["Total aset",b.totalAssets],["Utang usaha",journal.ap],["Piutang usaha",journal.ar]].map(([label,value])=><div key={String(label)} style={{background:"white",border:`1px solid ${c.line}`,borderRadius:9,padding:11}}><div style={{fontSize:9,color:c.med,fontWeight:700}}>{String(label)}</div><b style={{display:"block",fontSize:15,marginTop:6,color:Number(value)<0?c.red:c.ink}}>{rp(Number(value))}</b></div>)}</div><section style={{background:"white",border:`1px solid ${c.line}`,borderRadius:10,overflow:"hidden"}}><div style={{padding:"11px 13px",borderBottom:`1px solid ${c.line}`,display:"flex",alignItems:"center",gap:6,fontSize:12,fontWeight:800}}><Scale size={15} color={c.accent}/>Kontrol keseimbangan</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))"}}>{[["Aset",b.totalAssets],["Liabilitas + ekuitas",b.totalLiabilitiesAndEquity],["Selisih neraca",b.difference],["Kas operasional vs jurnal",operational.cash-journal.cash],["Piutang operasional vs jurnal",operational.ar-journal.ar],["Utang operasional vs jurnal",operational.ap-journal.ap]].map(([label,value])=><div key={String(label)} style={{padding:"10px 13px",borderBottom:`1px solid ${c.soft}`}}><div style={{fontSize:9,color:c.med}}>{String(label)}</div><b style={{fontSize:12,display:"block",marginTop:4,color:String(label).includes("Selisih")&&Math.abs(Number(value))>1?c.red:c.ink}}>{rp(Number(value))}</b></div>)}</div></section><section style={{background:"white",border:`1px solid ${c.line}`,borderRadius:10,overflow:"hidden"}}><div style={{padding:"11px 13px",fontSize:12,fontWeight:800,borderBottom:`1px solid ${c.line}`}}>Kinerja bulanan</div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:720,fontSize:9}}><thead><tr style={{background:c.soft}}>{["Bulan","Pendapatan","HPP","Laba kotor","Beban operasi","Laba bersih"].map(label=><th key={label} style={{padding:8,textAlign:label==="Bulan"?"left":"right"}}>{label}</th>)}</tr></thead><tbody>{report.monthly.map(row=><tr key={row.month} style={{borderBottom:`1px solid ${c.soft}`}}><td style={{padding:8,fontWeight:700}}>{MONTHS[row.month-1]}</td>{[row.revenue,row.cogs,row.grossProfit,row.operatingExpenses,row.netProfit].map((value,index)=><td key={index} style={{padding:8,textAlign:"right",color:index===4&&value<0?c.red:c.ink}}>{rp(value)}</td>)}</tr>)}</tbody></table></div></section></>}
function ProfitStatement({income,salesHpp}:{income:Report["incomeStatement"];salesHpp:SalesHppRecognitionRow[]}){const managementHpp=salesHpp.reduce((value,row)=>value+Number(row.total_hpp),0),managementRevenue=salesHpp.reduce((value,row)=>value+Number(row.revenue_total),0);return <div style={{display:"grid",gap:10}}><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:8}}>{[["Omzet barang terkirim",managementRevenue],["HPP lengkap per barang",managementHpp],["HPP yang masuk jurnal",income.totalCogs],["Selisih perlu rekonsiliasi",managementHpp-income.totalCogs]].map(([label,value])=><div key={String(label)} style={{background:"white",border:`1px solid ${c.line}`,borderRadius:9,padding:11}}><div style={{fontSize:9,color:c.med}}>{String(label)}</div><b style={{display:"block",fontSize:13,marginTop:5,color:String(label).includes("Selisih")&&Math.abs(Number(value))>1?c.red:c.ink}}>{rp(Number(value))}</b></div>)}</section><section style={{background:"white",border:`1px solid ${c.line}`,borderRadius:10,overflow:"hidden"}}><StatementSection title="Pendapatan usaha" rows={income.mainRevenue}/><StatementSection title="Retur dan potongan" rows={income.salesReturns}/><div style={{display:"flex",justifyContent:"space-between",padding:"10px 13px",background:c.paper,fontSize:11,fontWeight:800}}><span>Pendapatan bersih</span><span>{rp(income.netRevenue)}</span></div><StatementSection title="Harga pokok penjualan" rows={income.cogs} totalLabel="Total HPP" totalValue={income.totalCogs}/><div style={{display:"flex",justifyContent:"space-between",padding:"11px 13px",fontSize:12,fontWeight:900,color:c.green}}><span>Laba kotor</span><span>{rp(income.grossProfit)}</span></div><StatementSection title="Beban operasional" rows={income.operatingExpenses} totalLabel="Total beban operasional" totalValue={income.totalOperatingExpenses}/><StatementSection title="Pendapatan lain" rows={income.otherIncome}/><StatementSection title="Beban lain" rows={income.otherExpenses}/><StatementSection title="Beban pajak penghasilan" rows={income.taxExpenses}/><div style={{display:"flex",justifyContent:"space-between",padding:13,background:c.soft,fontSize:13,fontWeight:900,color:income.netProfit<0?c.red:c.green}}><span>Laba bersih</span><span>{rp(income.netProfit)}</span></div></section></div>}
function PositionStatement({balance:b}:{balance:Report["balanceSheet"]}){return <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(310px,1fr))",gap:10}}><div style={{background:"white",border:`1px solid ${c.line}`,borderRadius:10,overflow:"hidden"}}><div style={{padding:"11px 13px",fontSize:12,fontWeight:800,borderBottom:`1px solid ${c.line}`}}>Aset</div><StatementSection title="Aset lancar" rows={b.currentAssets}/><StatementSection title="Aset tidak lancar" rows={[...b.nonCurrentAssets,...b.contraAssets]}/><div style={{display:"flex",justifyContent:"space-between",padding:13,background:c.soft,fontWeight:900,fontSize:12}}><span>Total aset</span><span>{rp(b.totalAssets)}</span></div></div><div style={{background:"white",border:`1px solid ${c.line}`,borderRadius:10,overflow:"hidden"}}><div style={{padding:"11px 13px",fontSize:12,fontWeight:800,borderBottom:`1px solid ${c.line}`}}>Liabilitas dan ekuitas</div><StatementSection title="Liabilitas jangka pendek" rows={b.currentLiabilities}/><StatementSection title="Liabilitas jangka panjang" rows={b.nonCurrentLiabilities}/><StatementSection title="Ekuitas tercatat" rows={b.equity}/><StatementSection title="Laba yang belum ditutup" rows={[{id:"prior",code:"",name:"Akumulasi laba periode sebelumnya",amount:b.priorUnclosedEarnings},{id:"current",code:"",name:"Laba tahun berjalan",amount:b.currentEarnings}]}/><div style={{display:"flex",justifyContent:"space-between",padding:13,background:c.soft,fontWeight:900,fontSize:12}}><span>Total liabilitas dan ekuitas</span><span>{rp(b.totalLiabilitiesAndEquity)}</span></div></div><div style={{gridColumn:"1 / -1",padding:10,border:`1px solid ${Math.abs(b.difference)<=1?"#BBE2C5":"#FECACA"}`,background:Math.abs(b.difference)<=1?"#F0FBF3":"#FEF2F2",borderRadius:8,fontSize:10,color:Math.abs(b.difference)<=1?c.green:c.red,fontWeight:800}}>Selisih neraca: {rp(b.difference)} {Math.abs(b.difference)<=1?"· seimbang":"· periksa saldo awal dan jurnal periode sebelumnya"}</div></section>}
function CashAndEquity({report}:{report:Report}){return <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",gap:10}}><div style={{background:"white",border:`1px solid ${c.line}`,borderRadius:10,overflow:"hidden"}}><div style={{padding:"11px 13px",fontSize:12,fontWeight:800,borderBottom:`1px solid ${c.line}`}}>Arus kas metode langsung</div><div style={{overflowX:"auto",maxHeight:520}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:620,fontSize:9}}><thead><tr style={{background:c.soft}}>{["Tanggal","Referensi","Keterangan","Klasifikasi","Nilai"].map(label=><th key={label} style={{padding:8,textAlign:label==="Nilai"?"right":"left",position:"sticky",top:0,background:c.soft}}>{label}</th>)}</tr></thead><tbody>{report.cashFlow.rows.map(row=><tr key={row.id} style={{borderBottom:`1px solid ${c.soft}`}}><td style={{padding:8}}>{row.date}</td><td style={{padding:8,color:c.med}}>{row.reference}</td><td style={{padding:8}}>{row.description}</td><td style={{padding:8}}>{row.classification==="operating"?"Operasi":row.classification==="investing"?"Investasi":"Pendanaan"}</td><td style={{padding:8,textAlign:"right",fontWeight:700,color:row.amount<0?c.red:c.green}}>{rp(row.amount)}</td></tr>)}</tbody></table></div></div><div style={{display:"grid",gap:10,alignContent:"start"}}>{[["Ringkasan arus kas",[["Aktivitas operasi",report.cashFlow.operating],["Aktivitas investasi",report.cashFlow.investing],["Aktivitas pendanaan",report.cashFlow.financing],["Perubahan kas bersih",report.cashFlow.netChange]]],["Perubahan ekuitas",[["Saldo awal",report.equity.opening],["Setoran modal",report.equity.ownerContributions],["Prive owner",-report.equity.drawings],["Laba tahun berjalan",report.equity.currentProfit],["Saldo akhir",report.equity.closing]]]].map(([title,rows])=><div key={String(title)} style={{background:"white",border:`1px solid ${c.line}`,borderRadius:10,padding:12}}><div style={{fontSize:12,fontWeight:800}}>{String(title)}</div>{(rows as Array<[string,number]>).map(([label,value])=><div key={label} style={{display:"flex",justifyContent:"space-between",gap:8,padding:"8px 0",borderBottom:`1px solid ${c.soft}`,fontSize:10}}><span>{label}</span><b>{rp(value)}</b></div>)}</div>)}</div></section>}
function TrialBalance({report}:{report:Report}){return <section style={{background:"white",border:`1px solid ${c.line}`,borderRadius:10,overflow:"hidden"}}><div style={{overflowX:"auto",maxHeight:620}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:850,fontSize:9}}><thead><tr style={{background:c.soft}}>{["Kode","Akun","Saldo awal","Debit periode","Kredit periode","Saldo debit","Saldo kredit"].map(label=><th key={label} style={{padding:8,textAlign:label==="Kode"||label==="Akun"?"left":"right",position:"sticky",top:0,background:c.soft}}>{label}</th>)}</tr></thead><tbody>{report.trialBalance.map(row=><tr key={row.id} style={{borderBottom:`1px solid ${c.soft}`}}><td style={{padding:8,color:c.med}}>{row.code}</td><td style={{padding:8,fontWeight:700}}>{row.name}</td>{[row.opening,row.periodDebit,row.periodCredit,row.closingDebit,row.closingCredit].map((value,index)=><td key={index} style={{padding:8,textAlign:"right"}}>{rp(value)}</td>)}</tr>)}</tbody><tfoot><tr style={{background:c.paper,fontWeight:900}}><td colSpan={3} style={{padding:9}}>Total mutasi periode</td><td style={{padding:9,textAlign:"right"}}>{rp(report.trialBalance.reduce((v,r)=>v+r.periodDebit,0))}</td><td style={{padding:9,textAlign:"right"}}>{rp(report.trialBalance.reduce((v,r)=>v+r.periodCredit,0))}</td><td style={{padding:9,textAlign:"right"}}>{rp(report.trialBalance.reduce((v,r)=>v+r.closingDebit,0))}</td><td style={{padding:9,textAlign:"right"}}>{rp(report.trialBalance.reduce((v,r)=>v+r.closingCredit,0))}</td></tr></tfoot></table></div></section>}
function GeneralLedger({data,ledgerAccount,setLedgerAccount,ledger}:{data:Data;ledgerAccount:string;setLedgerAccount:(id:string)=>void;ledger:ReturnType<typeof buildGeneralLedger>|null}){return <section style={{background:"white",border:`1px solid ${c.line}`,borderRadius:10,overflow:"hidden"}}><div style={{padding:12,borderBottom:`1px solid ${c.line}`,display:"flex",alignItems:"end",gap:9,flexWrap:"wrap"}}><label style={{fontSize:9,fontWeight:700,color:c.med}}>Pilih akun<select value={ledgerAccount} onChange={event=>setLedgerAccount(event.target.value)} style={{display:"block",marginTop:4,border:`1px solid ${c.line}`,borderRadius:7,padding:"8px 9px",fontSize:10,minWidth:260}}><option value="">Pilih akun buku besar</option>{data.accounts.map(account=><option key={account.id} value={account.id}>{account.code} · {account.name}</option>)}</select></label>{ledger?.account?<div style={{fontSize:10,color:c.med}}>Saldo awal <b style={{color:c.ink}}>{rp(ledger.opening)}</b> · saldo akhir <b style={{color:c.ink}}>{rp(ledger.closing)}</b></div>:null}</div>{ledger?.account?<div style={{overflowX:"auto",maxHeight:560}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:720,fontSize:9}}><thead><tr style={{background:c.soft}}>{["Tanggal","Referensi","Keterangan","Debit","Kredit","Saldo"].map(label=><th key={label} style={{padding:8,textAlign:["Debit","Kredit","Saldo"].includes(label)?"right":"left",position:"sticky",top:0,background:c.soft}}>{label}</th>)}</tr></thead><tbody>{ledger.rows.map(row=><tr key={row.id} style={{borderBottom:`1px solid ${c.soft}`}}><td style={{padding:8}}>{row.date}</td><td style={{padding:8,color:c.med}}>{row.reference}</td><td style={{padding:8}}>{row.description}</td><td style={{padding:8,textAlign:"right"}}>{rp(row.debit)}</td><td style={{padding:8,textAlign:"right"}}>{rp(row.credit)}</td><td style={{padding:8,textAlign:"right",fontWeight:800}}>{rp(row.balance)}</td></tr>)}</tbody></table></div>:<div style={{padding:24,textAlign:"center",fontSize:10,color:c.med}}><BookOpen size={20} style={{margin:"0 auto 7px"}}/>Pilih akun untuk melihat mutasi dan saldo berjalan.</div>}</section>}
type AgingRow={invoice:string;customer?:string;supplier?:string;date:string;days:number;bucket:string;amount:number};
function Subledgers({receivables,payables,journal}:{receivables:AgingRow[];payables:AgingRow[];journal:{ar:number;ap:number}}){const ar=sumAging(receivables),ap=sumAging(payables);return <div style={{display:"grid",gap:10}}><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:8}}>{[["Piutang operasional",ar],["Saldo akun piutang",journal.ar],["Selisih piutang",ar-journal.ar],["Utang operasional",ap],["Saldo akun utang",journal.ap],["Selisih utang",ap-journal.ap]].map(([label,value])=><div key={String(label)} style={{background:"white",border:`1px solid ${c.line}`,borderRadius:9,padding:11}}><div style={{fontSize:9,color:c.med}}>{String(label)}</div><b style={{display:"block",fontSize:13,marginTop:5,color:String(label).includes("Selisih")&&Math.abs(Number(value))>1?c.red:c.ink}}>{rp(Number(value))}</b></div>)}</section><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(420px,1fr))",gap:10}}><AgingTable title="Daftar umur piutang" rows={receivables} party="customer"/><AgingTable title="Daftar umur utang" rows={payables} party="supplier"/></section><div style={{fontSize:9,color:c.med,padding:9,background:c.paper,borderRadius:7}}>Daftar umur memakai status pembayaran terbaru dari menu Pesanan dan Tagihan Bahan. Histori pembayaran diperlukan untuk melihat posisi masa lalu secara tepat.</div></div>}
function sumAging(rows:AgingRow[]){return rows.reduce((value,row)=>value+row.amount,0)}
function AgingTable({title,rows,party}:{title:string;rows:AgingRow[];party:"customer"|"supplier"}){return <div style={{background:"white",border:`1px solid ${c.line}`,borderRadius:10,overflow:"hidden"}}><div style={{padding:"11px 13px",fontSize:12,fontWeight:800,borderBottom:`1px solid ${c.line}`}}>{title}</div><div style={{overflowX:"auto",maxHeight:500}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:530,fontSize:9}}><thead><tr style={{background:c.soft}}>{["Invoice",party==="customer"?"Customer":"Supplier","Tanggal","Umur","Kelompok","Sisa"].map(label=><th key={label} style={{padding:8,textAlign:label==="Sisa"?"right":"left",position:"sticky",top:0,background:c.soft}}>{label}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={`${row.invoice}:${row.date}`} style={{borderBottom:`1px solid ${c.soft}`}}><td style={{padding:8,fontWeight:700}}>{row.invoice}</td><td style={{padding:8}}>{row.customer??row.supplier}</td><td style={{padding:8}}>{row.date}</td><td style={{padding:8}}>{row.days} hari</td><td style={{padding:8,color:row.bucket===">90"?c.red:c.med,fontWeight:700}}>{row.bucket}</td><td style={{padding:8,textAlign:"right",fontWeight:800}}>{rp(row.amount)}</td></tr>)}{!rows.length?<tr><td colSpan={6} style={{padding:20,textAlign:"center",color:c.med}}>Tidak ada saldo terbuka.</td></tr>:null}</tbody></table></div></div>}
